#!/bin/bash
echo "=== 原生VNC启动失败问题分析 ==="
echo ""

echo "1. 检查关键文件状态:"
echo "   libqemu_full.so (oh_modules): $(ls -la entry/oh_modules/libqemu_full.so 2>/dev/null && echo '✅ 存在' || echo '❌ 缺失')"
echo "   libqemu_hmos.so (oh_modules): $(ls -la entry/oh_modules/libqemu_hmos.so 2>/dev/null && echo '✅ 存在' || echo '❌ 缺失')"
echo "   libvncclient.a: $(ls -la entry/src/main/cpp/third_party/libvncclient/libvncclient.a 2>/dev/null && echo '✅ 存在' || echo '❌ 缺失')"
echo ""

echo "2. 预期启动流程:"
echo "   步骤1: VNCNativeViewer页面加载"
echo "   步骤2: 检查vnc.isAvailable() - 应返回true"
echo "   步骤3: 调用qemu.startVm() - 配置display='vnc=:1'"
echo "   步骤4: VM启动后等待2秒"
echo "   步骤5: 调用vnc.connect('127.0.0.1', 5901)"
echo "   步骤6: 显示连接结果"
echo ""

echo "3. 可能的VM启动失败原因:"
echo "   ❌ 磁盘文件不存在 - VM需要有效的磁盘镜像"
echo "   ❌ 固件文件路径错误 - QEMU找不到UEFI固件"
echo "   ❌ QEMU参数错误 - 命令行参数格式问题"
echo "   ❌ 权限问题 - HarmonyOS应用权限不足"
echo "   ❌ 内存不足 - VM内存分配失败"
echo "   ❌ TCG加速器问题 - ARM64架构兼容性"
echo ""

echo "4. 关键日志检查命令:"
echo "   # 查看QEMU启动日志"
echo "   hdc shell hilog -x | grep -E '(QEMU|qemu_main|VM启动)' | tail -10"
echo ""
echo "   # 查看VM状态日志"
echo "   hdc shell hilog -x | grep -E '(VNC_NATIVE|启动失败)' | tail -10"
echo ""

echo "5. VM配置验证:"
echo "   预期磁盘路径: /data/storage/el2/base/haps/entry/files/vms/zhubizi/disk.qcow2"
echo "   预期日志路径: /data/storage/el2/base/haps/entry/files/vms/zhubizi/qemu.log"
echo "   预期固件路径: edk2-aarch64-code.fd (HAP内部)"
echo ""

echo "6. 增强的诊断步骤:"
echo "   a) 重新安装最新HAP文件"
echo "   b) 检查VM目录权限: /data/storage/el2/base/haps/entry/files/vms/"
echo "   c) 查看QEMU详细日志输出"
echo "   d) 检查磁盘文件是否正确创建"
echo "   e) 验证固件文件路径映射"
echo ""

echo "7. 手动测试步骤:"
echo "   1. 重新编译: hvigor assembleApp"
echo "   2. 重新安装: hdc install -r entry/build/default/outputs/default/entry-default-signed.hap"
echo "   3. 启动应用，进入原生VNC页面"
echo "   4. 点击'启动并连接原生VNC'"
echo "   5. 立即查看hilog日志，关注QEMU相关输出"
echo "   6. 检查VM目录中是否生成了日志文件"
