name: Build QEMU with Linux GCC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake curl wget unzip python3 \
                              libglib2.0-dev libpixman-1-dev libssl-dev \
                              libcurl4-openssl-dev libssh-dev libgnutls28-dev \
                              libsasl2-dev libpam0g-dev libbz2-dev libzstd-dev \
                              libpcre2-dev pkg-config meson tree \
                              gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build QEMU with system cross-compiler
      run: |
        echo "=== Building QEMU with system cross-compiler ==="
        cd third_party/qemu
        
        mkdir -p build
        cd build
        
        echo "Using system cross-compiler:"
        echo "CC: aarch64-linux-gnu-gcc"
        echo "CXX: aarch64-linux-gnu-g++"
        
        # Test compiler first
        echo "Testing compiler:"
        aarch64-linux-gnu-gcc --version | head -3
        
        echo ""
        echo "=== Running Configure ==="
        ../configure \
          --target-list=aarch64-softmmu \
          --cc=aarch64-linux-gnu-gcc \
          --cxx=aarch64-linux-gnu-g++ \
          --host-cc=gcc \
          --cross-prefix=aarch64-linux-gnu- \
          --enable-tcg \
          --disable-kvm \
          --disable-xen \
          --disable-werror \
          --enable-vnc \
          --enable-slirp \
          --enable-curl \
          --enable-fdt \
          --enable-guest-agent \
          --enable-vhost-user \
          --enable-vhost-net \
          --enable-keyring \
          --disable-gtk \
          --disable-sdl \
          --disable-vte \
          --disable-curses \
          --disable-brlapi \
          --disable-spice \
          --disable-usb-redir \
          --disable-lzo \
          --disable-snappy \
          --disable-bzip2 \
          --disable-lzfse \
          --disable-zstd \
          --disable-libssh \
          --disable-nettle \
          --disable-gcrypt \
          --disable-gnutls \
          --disable-nss
        
        echo "✅ Configure completed!"
        
        echo "=== Building QEMU ==="
        make -j$(nproc)
        
        echo "✅ QEMU build completed!"
        
        echo "=== Checking build results ==="
        ls -la qemu-system-aarch64 || echo "Main binary not found"
        find . -name "*.so" -o -name "*.a" | head -10

    - name: Build NAPI module with system compiler
      run: |
        echo "=== Building NAPI module ==="
        cd entry/src/main/cpp
        
        mkdir -p build
        cd build
        
        echo "Using system CMake and cross-compiler"
        
        cmake .. \
          -DCMAKE_SYSTEM_NAME=Linux \
          -DCMAKE_SYSTEM_PROCESSOR=aarch64 \
          -DCMAKE_C_COMPILER=aarch64-linux-gnu-gcc \
          -DCMAKE_CXX_COMPILER=aarch64-linux-gnu-g++ \
          -DCMAKE_FIND_ROOT_PATH_MODE_PROGRAM=NEVER \
          -DCMAKE_FIND_ROOT_PATH_MODE_LIBRARY=ONLY \
          -DCMAKE_FIND_ROOT_PATH_MODE_INCLUDE=ONLY
        
        make -j$(nproc)
        
        echo "✅ NAPI module build completed!"
        
        echo "=== Build artifacts ==="
        ls -la *.so || echo "No .so files found"
        find . -name "*.so" -o -name "*.a"

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-system-gcc-build
        path: |
          third_party/qemu/build/qemu-system-aarch64
          third_party/qemu/build/*.so
          third_party/qemu/build/*.a
          entry/src/main/cpp/build/*.so
        retention-days: 7
