name: Simple QEMU Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-simple:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - name: Setup environment
      run: |
        echo "Setting up build environment..."
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          ninja-build \
          pkg-config \
          libglib2.0-dev \
          libpixman-1-dev \
          libssl-dev \
          libcurl4-openssl-dev \
          libssh-dev \
          libgnutls28-dev \
          libsasl2-dev \
          libpam0g-dev \
          libbz2-dev \
          libzstd-dev \
          libpcre2-dev \
          python3 \
          python3-pip \
          meson \
          cmake \
          git \
          wget \
          unzip

    - name: Download HarmonyOS SDK
      run: |
        echo "Downloading HarmonyOS SDK..."
        wget -O harmonyos-sdk.zip "https://contentcenter-vali-drcn.dbankcdn.cn/pvt_2/DeveloperAlliance_package_901_9/f1/v3/VhLKThVXTe6w9PHylZ0IxA/commandline-tools-linux-x64-6.0.0.848.zip?HW-CC-KV=V1&HW-CC-Date=20250924T181625Z&HW-CC-Expire=7200&HW-CC-Sign=9AF08E32538FCAF37F97DD9110A4A5FF162146FE5A794ED41ED9BBC4DD426926"
        
        echo "Extracting HarmonyOS SDK..."
        unzip -q harmonyos-sdk.zip
        
        echo "Checking extracted contents..."
        ls -la
        
        echo "Looking for SDK directory..."
        find . -name "*sdk*" -type d | head -10
        find . -name "*openharmony*" -type d | head -10
        find . -name "*native*" -type d | head -10
        
        # Try different possible directory structures
        if [ -d "commandline-tools" ]; then
          echo "Found commandline-tools directory"
          sudo mv commandline-tools /opt/harmonyos-sdk
        elif [ -d "sdk" ]; then
          echo "Found sdk directory"
          sudo mv sdk /opt/harmonyos-sdk
        else
          echo "Listing all directories to find the correct one:"
          ls -la
          echo "Creating symlink to current directory"
          sudo ln -s $(pwd) /opt/harmonyos-sdk
        fi
        
        sudo chmod -R 755 /opt/harmonyos-sdk

    - name: Verify SDK installation
      run: |
        echo "Verifying HarmonyOS SDK installation..."
        echo "SDK root directory:"
        ls -la /opt/harmonyos-sdk/
        
        echo "Looking for NDK structure..."
        find /opt/harmonyos-sdk -name "llvm" -type d | head -5
        find /opt/harmonyos-sdk -name "cmake" -type d | head -5
        find /opt/harmonyos-sdk -name "clang" -type f | head -5
        
        # Try to find the correct paths
        if [ -d "/opt/harmonyos-sdk/sdk/default/openharmony/native/llvm/bin" ]; then
          echo "Found standard NDK structure"
          ls -la /opt/harmonyos-sdk/sdk/default/openharmony/native/llvm/bin/
        else
          echo "Looking for alternative NDK structure..."
          find /opt/harmonyos-sdk -name "aarch64-unknown-linux-ohos-clang" -type f
          find /opt/harmonyos-sdk -name "cmake" -type f
        fi

    - name: Run simplified build
      run: |
        echo "Running simplified QEMU build..."
        chmod +x scripts/build-qemu-simple.sh
        ./scripts/build-qemu-simple.sh

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: qemu-harmonyos-simple
        path: |
          entry/src/main/libs/arm64-v8a/
          entry/src/main/oh_modules/
        retention-days: 30

    - name: Build summary
      run: |
        echo "=== Build Summary ==="
        echo "Build type: Simplified (minimal dependencies)"
        echo "Target: aarch64-linux-ohos"
        echo ""
        echo "Generated files:"
        ls -la entry/src/main/libs/arm64-v8a/
        echo ""
        echo "File sizes:"
        du -h entry/src/main/libs/arm64-v8a/*
        echo ""
        echo "Build completed successfully!"
