name: Build QEMU-HMOS (Robust)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Install minimal deps (host tools only)
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential curl wget unzip python3 python3-pip pkg-config

    - name: Upgrade Meson (>=1.5) & Ninja
      run: |
        python3 -m pip install --upgrade --user 'meson>=1.5.0' 'ninja>=1.11'
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        which meson && meson --version
        which ninja && ninja --version

    - name: Prepare Meson cross file
      run: |
        set -e
        mkdir -p cross
        cat > cross/aarch64-ohos.ini <<EOF
        [binaries]
        c = '${CC}'
        cpp = '${CXX}'
        ar = '${AR}'
        strip = '${STRIP}'
        pkg-config = 'pkg-config'
        ld = '${CC}'

        [host_machine]
        system = 'linux'
        cpu_family = 'aarch64'
        cpu = 'armv8'
        endian = 'little'

        [built-in options]
        sys_root = '${SYSROOT}'
        c_args = ['--sysroot=${SYSROOT}','-fPIC','-O2','-pipe','-fvisibility=hidden']
        cpp_args = ['--sysroot=${SYSROOT}','-fPIC','-O2','-pipe','-fvisibility=hidden']
        c_link_args = ['--sysroot=${SYSROOT}']
        cpp_link_args = ['--sysroot=${SYSROOT}']
        EOF
        echo "Cross file written to: $GITHUB_WORKSPACE/cross/aarch64-ohos.ini"
        ls -la cross
        echo "Preview:"
        sed -n '1,30p' cross/aarch64-ohos.ini
