name: Debug SDK Only

on:
  workflow_dispatch:

jobs:
  debug-sdk:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Install basic dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          pkg-config \
          wget \
          unzip \
          tree

    - name: Download HarmonyOS SDK
      run: |
        echo "=== Downloading HarmonyOS SDK ==="
        wget -O harmonyos-sdk.zip "https://contentcenter-vali-drcn.dbankcdn.cn/pvt_2/DeveloperAlliance_package_901_9/f1/v3/VhLKThVXTe6w9PHylZ0IxA/commandline-tools-linux-x64-6.0.0.848.zip?HW-CC-KV=V1&HW-CC-Date=20250924T181625Z&HW-CC-Expire=7200&HW-CC-Sign=9AF08E32538FCAF37F97DD9110A4A5FF162146FE5A794ED41ED9BBC4DD426926"
        
        echo "=== File info ==="
        ls -la harmonyos-sdk.zip
        file harmonyos-sdk.zip
        
        echo "=== Extracting SDK ==="
        unzip -q harmonyos-sdk.zip
        
        echo "=== Analyzing extracted structure ==="
        echo "Root directory contents:"
        ls -la
        
        echo "=== Directory tree (first 3 levels) ==="
        tree -L 3 || find . -maxdepth 3 -type d | sort

    - name: Run SDK debug script
      run: |
        echo "=== Running SDK Debug Script ==="
        chmod +x scripts/debug-sdk-paths.sh
        
        # Try different possible SDK locations
        if [ -d "commandline-tools" ]; then
          echo "Found commandline-tools directory"
          sudo mv commandline-tools /opt/harmonyos-sdk
        elif [ -d "sdk" ]; then
          echo "Found sdk directory"
          sudo mv sdk /opt/harmonyos-sdk
        else
          echo "Creating symlink to current directory"
          sudo ln -s $(pwd) /opt/harmonyos-sdk
        fi
        
        sudo chmod -R 755 /opt/harmonyos-sdk
        
        # Run debug script
        ./scripts/debug-sdk-paths.sh

    - name: Test local build
      run: |
        echo "=== Testing Local Build ==="
        chmod +x scripts/build-local-test.sh
        ./scripts/build-local-test.sh

    - name: Archive debug results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: debug-results
        path: |
          third_party/qemu/build_local_test/*.a
          third_party/qemu/build_local_test/*.so
        retention-days: 1
