name: Quick Build Test

on:
  workflow_dispatch:
    inputs:
      test_type:
        description: 'Test type'
        required: true
        default: 'full'
        type: choice
        options:
        - full
        - qemu-only
        - napi-only

jobs:
  quick-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: false

    - name: Setup basic environment
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build pkg-config

    - name: Download HarmonyOS SDK
      run: |
        wget -O harmonyos-sdk.zip "https://contentcenter-vali-drcn.dbankcdn.cn/pvt_2/DeveloperAlliance_package_901_9/f1/v3/VhLKThVXTe6w9PHylZ0IxA/commandline-tools-linux-x64-6.0.0.848.zip?HW-CC-KV=V1&HW-CC-Date=20250924T181625Z&HW-CC-Expire=7200&HW-CC-Sign=9AF08E32538FCAF37F97DD9110A4A5FF162146FE5A794ED41ED9BBC4DD426926"
        unzip -q harmonyos-sdk.zip
        
        # Try different possible directory structures
        if [ -d "commandline-tools" ]; then
          sudo mv commandline-tools /opt/harmonyos-sdk
        elif [ -d "sdk" ]; then
          sudo mv sdk /opt/harmonyos-sdk
        else
          sudo ln -s $(pwd) /opt/harmonyos-sdk
        fi

    - name: Run build script
      run: |
        chmod +x scripts/build-qemu-cloud.sh
        ./scripts/build-qemu-cloud.sh

    - name: Quick verification
      run: |
        echo "=== Quick Verification ==="
        ls -la entry/src/main/libs/arm64-v8a/
        file entry/src/main/libs/arm64-v8a/*
        echo "Build completed in $(date)"
